"""adiciona bloqueio de conta em user

Revision ID: 01a01055b1af
Revises: f8fe7ce9347c
Create Date: 2026-09-17 19:36:02.143995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a01055b1af'
down_revision: Union[str, Sequence[str], None] = 'f8fe7ce9347c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locked_until')
    op.drop_column('user', 'failed_login_attempts')
    # ### end Alembic commands ###
