"""competency unica por label e equipment_family

Revision ID: 06e73a1db53b
Revises: d5c54063c1fb
Create Date: 2026-08-21 17:27:16.965409

"""
from typing import Sequence, Union, cast

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '06e73a1db53b'
down_revision: Union[str, Sequence[str], None] = 'd5c54063c1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competency', sa.Column('equipment_family', sa.String(), server_default='TOMOGRAFO', nullable=False))
    op.drop_constraint(op.f('competency_label_key'), 'competency', type_='unique')
    op.create_unique_constraint(None, 'competency', ['label', 'equipment_family'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `None` é o nome deliberadamente omitido na revisão original; o cast só
    # informa isso ao verificador estático e não muda o valor em runtime.
    op.drop_constraint(cast(str, None), 'competency', type_='unique')
    op.create_unique_constraint(op.f('competency_label_key'), 'competency', ['label'], postgresql_nulls_not_distinct=False)
    op.drop_column('competency', 'equipment_family')
    # ### end Alembic commands ###
