"""colapsa config_decision e config_decision_history em tabela unica append-only

Revision ID: 28c0d8de92f2
Revises: f599d15640e4
Create Date: 2026-08-24 09:48:07.058664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28c0d8de92f2'
down_revision: Union[str, Sequence[str], None] = 'f599d15640e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_decision_history')
    op.add_column('config_decision', sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('config_decision', sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('config_decision_key_key'), 'config_decision', type_='unique')
    op.create_index('ux_config_decision_key_vigente', 'config_decision', ['key'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_column('config_decision', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_decision', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('ux_config_decision_key_vigente', table_name='config_decision', postgresql_where=sa.text('valid_to IS NULL'))
    op.create_unique_constraint(op.f('config_decision_key_key'), 'config_decision', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_column('config_decision', 'valid_to')
    op.drop_column('config_decision', 'valid_from')
    op.create_table('config_decision_history',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('config_decision_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confirmed_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['config_decision_id'], ['config_decision.id'], name=op.f('config_decision_history_config_decision_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['user.id'], name=op.f('config_decision_history_confirmed_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('config_decision_history_pkey'))
    )
    # ### end Alembic commands ###
