"""adiciona macro_code e macro_name em equipment_offer_row

Revision ID: 2c5d169b43ac
Revises: 3654a7c5717b
Create Date: 2026-08-17 10:09:56.282366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5d169b43ac'
down_revision: Union[str, Sequence[str], None] = '3654a7c5717b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_offer_row', sa.Column('macro_code', sa.String(), nullable=True))
    op.add_column('equipment_offer_row', sa.Column('macro_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_offer_row', 'macro_name')
    op.drop_column('equipment_offer_row', 'macro_code')
    # ### end Alembic commands ###
