"""adiciona facility_name e municipality_name em equipment_offer_row

Revision ID: 3654a7c5717b
Revises: 92fe48aa5b7b
Create Date: 2026-08-14 10:43:19.062646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3654a7c5717b"
down_revision: Union[str, Sequence[str], None] = "92fe48aa5b7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_competency_published_execution",
        "competency",
        "execution",
        ["published_execution_id"],
        ["id"],
        ondelete="RESTRICT",
        use_alter=True,
    )
    op.add_column("equipment_offer_row", sa.Column("facility_name", sa.String(), nullable=True))
    op.add_column("equipment_offer_row", sa.Column("municipality_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("equipment_offer_row", "municipality_name")
    op.drop_column("equipment_offer_row", "facility_name")
    op.drop_constraint("fk_competency_published_execution", "competency", type_="foreignkey")
    # ### end Alembic commands ###
