"""add health_region_code and health_region_name to equipment_offer_row

Revision ID: 69b899c611d8
Revises: 2c5d169b43ac
Create Date: 2026-08-18 13:54:37.270011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b899c611d8'
down_revision: Union[str, Sequence[str], None] = '2c5d169b43ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_offer_row', sa.Column('health_region_code', sa.String(), nullable=True))
    op.add_column('equipment_offer_row', sa.Column('health_region_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_offer_row', 'health_region_name')
    op.drop_column('equipment_offer_row', 'health_region_code')
    # ### end Alembic commands ###
