"""adiciona situacao_ordem_pagamento_transferegov

Revision ID: 71608fab14e8
Revises: bd63b49ea150
Create Date: 2026-09-15 15:23:48.895980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71608fab14e8"
down_revision: Union[str, Sequence[str], None] = "bd63b49ea150"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instrumento_equipamento", sa.Column("situacao_ordem_pagamento_transferegov", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instrumento_equipamento", "situacao_ordem_pagamento_transferegov")
    # ### end Alembic commands ###
