"""convenio_valor_pago_fornecedor

Revision ID: 728d0f835ed7
Revises: adfca2ad8745
Create Date: 2026-09-16 14:03:27.304879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728d0f835ed7'
down_revision: Union[str, Sequence[str], None] = 'adfca2ad8745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convenio', sa.Column('valor_pago_fornecedor', sa.Numeric(), nullable=True))
    op.add_column('convenio', sa.Column('pagamentos_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('convenio', 'pagamentos_count')
    op.drop_column('convenio', 'valor_pago_fornecedor')
    # ### end Alembic commands ###
