"""initial schema

Revision ID: 92fe48aa5b7b
Revises: 
Create Date: 2026-08-10 17:10:08.920695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92fe48aa5b7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_execution_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['published_execution_id'], ['execution.id'], name='fk_competency_published_execution', ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('inca_estimate',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('level', sa.Enum('uf', 'capital', name='inca_estimate_level'), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('capital_ibge_code', sa.String(), nullable=True),
    sa.Column('estimated_cases', sa.Integer(), nullable=False),
    sa.Column('triennium', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('cpf_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'colaborador', 'leitor', name='user_role'), server_default='colaborador', nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='user_status'), server_default='active', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_decision',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('key', sa.Enum('chave_macrorregiao', 'denominador_oferta', 'metrica_cobertura', name='config_decision_key'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('reference_file',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('type', sa.Enum('accelerator', 'population', name='reference_file_type'), nullable=False),
    sa.Column('reference_period', sa.Date(), nullable=True),
    sa.Column('original_file', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accelerator_row',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('reference_file_id', sa.BigInteger(), nullable=False),
    sa.Column('cnes_code', sa.String(), nullable=False),
    sa.Column('facility_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('ibge_code', sa.String(), nullable=False),
    sa.Column('operational_qty', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['reference_file_id'], ['reference_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_decision_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('config_decision_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_decision_id'], ['config_decision.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('competency_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('manual', 'automatic', name='execution_mode'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='execution_status'), server_default='draft', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_by', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('config_chave_macrorregiao', sa.String(), nullable=False),
    sa.Column('config_denominador_oferta', sa.String(), nullable=False),
    sa.Column('accelerator_file_id', sa.BigInteger(), nullable=True),
    sa.Column('population_file_id', sa.BigInteger(), nullable=True),
    sa.Column('active_sources', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['accelerator_file_id'], ['reference_file.id'], ),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['executed_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['population_file_id'], ['reference_file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competency_id', 'version')
    )
    op.create_table('municipality_population_row',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('reference_file_id', sa.BigInteger(), nullable=False),
    sa.Column('ibge_code', sa.String(), nullable=False),
    sa.Column('resident_population', sa.Integer(), nullable=False),
    sa.Column('ans_population', sa.Integer(), nullable=False),
    sa.Column('sus_dependent_population', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_file_id'], ['reference_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_offer_row',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('execution_id', sa.BigInteger(), nullable=False),
    sa.Column('cnes_code', sa.String(), nullable=False),
    sa.Column('ibge_code', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('equipment_family', sa.String(), nullable=False),
    sa.Column('equipment_subtype', sa.String(), nullable=True),
    sa.Column('existing_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('in_use_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sus_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_alert',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('execution_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_type', sa.Enum('municipality_exception', 'macro_exception', 'macro_code_divergence', name='alert_type'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('macro_coverage',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('execution_id', sa.BigInteger(), nullable=False),
    sa.Column('macro_code', sa.String(), nullable=False),
    sa.Column('macro_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('equipment_family', sa.String(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('estimated_need', sa.Numeric(), nullable=True),
    sa.Column('required_qty', sa.Integer(), nullable=True),
    sa.Column('available_qty', sa.Integer(), nullable=True),
    sa.Column('existing_qty', sa.Integer(), nullable=True),
    sa.Column('facility_count', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('deficit_status', sa.Enum('deficient', 'not_deficient', 'not_available', name='deficit_status'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed: D-01 e D-02 ja confirmados (ver Caso de Uso, secao 1/6)
    op.execute("""
        INSERT INTO config_decision (key, value, confirmed, confirmed_at) VALUES
            ('chave_macrorregiao', 'ibge_municipio', true, now()),
            ('denominador_oferta', 'qt_existente_sus', true, now()),
            ('metrica_cobertura', 'binaria', false, NULL)
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_coverage')
    op.drop_table('execution_alert')
    op.drop_table('equipment_offer_row')
    op.drop_table('municipality_population_row')
    op.drop_table('execution')
    op.drop_table('config_decision_history')
    op.drop_table('accelerator_row')
    op.drop_table('reference_file')
    op.drop_table('config_decision')
    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_table('inca_estimate')
    op.drop_table('competency')
    # ### end Alembic commands ###
