"""adiciona cd_parceria em proposta_candidata

Revision ID: 971645318ac4
Revises: c214b6dc6a4a
Create Date: 2026-09-15 12:33:36.996173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "971645318ac4"
down_revision: Union[str, Sequence[str], None] = "c214b6dc6a4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("proposta_candidata", sa.Column("cd_parceria", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proposta_candidata", "cd_parceria")
    # ### end Alembic commands ###
