"""cnes_estabelecimento_convenio_proposta_cnes

Revision ID: adfca2ad8745
Revises: 71608fab14e8
Create Date: 2026-09-16 10:30:12.349544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adfca2ad8745'
down_revision: Union[str, Sequence[str], None] = '71608fab14e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnes_estabelecimento',
    sa.Column('cnes', sa.String(length=7), nullable=False),
    sa.Column('nome_estabelecimento', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cnes')
    )
    op.create_table('convenio',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('numero_instrumento', sa.String(), nullable=True),
    sa.Column('ano_instrumento', sa.Integer(), nullable=True),
    sa.Column('objeto', sa.String(), nullable=True),
    sa.Column('situacao', sa.String(), nullable=True),
    sa.Column('situacao_portal', sa.String(), nullable=True),
    sa.Column('situacao_contratacao', sa.String(), nullable=True),
    sa.Column('convenente_nome', sa.String(), nullable=False),
    sa.Column('convenente_cnpj', sa.String(), nullable=False),
    sa.Column('convenente_tipo', sa.String(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('codigo_ibge', sa.String(), nullable=True),
    sa.Column('regiao', sa.String(), nullable=True),
    sa.Column('orgao', sa.String(), nullable=True),
    sa.Column('unidade_gestora', sa.String(), nullable=True),
    sa.Column('subfuncao', sa.String(), nullable=True),
    sa.Column('funcao', sa.String(), nullable=True),
    sa.Column('tipo_instrumento', sa.String(), nullable=True),
    sa.Column('numero_processo', sa.String(), nullable=True),
    sa.Column('programa', sa.String(), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=True),
    sa.Column('data_final_vigencia', sa.Date(), nullable=True),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.Column('data_ultima_liberacao', sa.Date(), nullable=True),
    sa.Column('valor_global', sa.Numeric(), nullable=True),
    sa.Column('valor_repasse', sa.Numeric(), nullable=True),
    sa.Column('valor_empenhado', sa.Numeric(), nullable=True),
    sa.Column('valor_desembolsado', sa.Numeric(), nullable=True),
    sa.Column('valor_contrapartida', sa.Numeric(), nullable=True),
    sa.Column('valor_saldo_conta', sa.Numeric(), nullable=True),
    sa.Column('valor_ultima_liberacao', sa.Numeric(), nullable=True),
    sa.Column('financeiro_fonte_confiavel', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('equipamentos_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cnes', sa.String(length=7), nullable=True),
    sa.Column('cnes_metodo', sa.String(), nullable=True),
    sa.Column('siconv_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transferegov_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.add_column('proposta_candidata', sa.Column('cnes', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposta_candidata', 'cnes')
    op.drop_table('convenio')
    op.drop_table('cnes_estabelecimento')
    # ### end Alembic commands ###
