"""adiciona indices de leitura em equipment_offer_row e macro_coverage

Revision ID: b3a934a59718
Revises: 69b899c611d8
Create Date: 2026-08-19 17:15:45.029279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a934a59718'
down_revision: Union[str, Sequence[str], None] = '69b899c611d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_eor_execution_cnes', 'equipment_offer_row', ['execution_id', 'cnes_code'], unique=False)
    op.create_index('ix_eor_execution_family', 'equipment_offer_row', ['execution_id', 'equipment_family'], unique=False)
    op.create_index('ix_eor_execution_family_state', 'equipment_offer_row', ['execution_id', 'equipment_family', 'state'], unique=False)
    op.create_index('ix_eor_execution_health_region', 'equipment_offer_row', ['execution_id', 'health_region_code'], unique=False)
    op.create_index('ix_eor_execution_macro', 'equipment_offer_row', ['execution_id', 'macro_code'], unique=False)
    op.create_index('ix_eor_execution_municipality', 'equipment_offer_row', ['execution_id', 'municipality_name'], unique=False)
    op.create_index('ix_macro_coverage_execution_family', 'macro_coverage', ['execution_id', 'equipment_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_macro_coverage_execution_family', table_name='macro_coverage')
    op.drop_index('ix_eor_execution_municipality', table_name='equipment_offer_row')
    op.drop_index('ix_eor_execution_macro', table_name='equipment_offer_row')
    op.drop_index('ix_eor_execution_health_region', table_name='equipment_offer_row')
    op.drop_index('ix_eor_execution_family_state', table_name='equipment_offer_row')
    op.drop_index('ix_eor_execution_family', table_name='equipment_offer_row')
    op.drop_index('ix_eor_execution_cnes', table_name='equipment_offer_row')
    # ### end Alembic commands ###
