"""adiciona situacao_parceria_transferegov

Revision ID: bd63b49ea150
Revises: 971645318ac4
Create Date: 2026-09-15 15:21:06.815161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd63b49ea150"
down_revision: Union[str, Sequence[str], None] = "971645318ac4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("instrumento_equipamento", sa.Column("situacao_parceria_transferegov", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instrumento_equipamento", "situacao_parceria_transferegov")
    # ### end Alembic commands ###
