"""adiciona proposta_candidata e notificacao (radar de convenios)

Revision ID: c214b6dc6a4a
Revises: d1e2f3a4b5c6
Create Date: 2026-09-15 10:38:13.278748

Fluxo completo em docs/arquitetura/fluxo_requisicao.md, schema em
docs/database/modelo_er.md (fechado com o usuario 2026-09-15).

- proposta_candidata: 1 linha por proposta do TransfereGov novo achada pelo
  job de descoberta (ainda a implementar), pendente de revisao humana.
  id_proposta (TransfereGov) e a chave de dedup -- nunca comparada contra
  nr_convenio/cnpj do SICONV legado (universos disjuntos).
- notificacao: 2 camadas (atualizacao vinda de API vs edicao manual do
  tecnico) + notificacao de candidato pendente. entidade_id e polimorfico
  por tipo, sem FK fisica de proposito, mesmo padrao ja usado por
  AuditLog.entity_name/entity_id.

Sem alteracao em instrumento_equipamento aqui -- o endpoint de criacao
(POST /monitoramento/instrumentos) e o job de descoberta/verificacao ficam
pra proxima rodada, essa migration so prepara o schema.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c214b6dc6a4a"
down_revision: Union[str, Sequence[str], None] = "d1e2f3a4b5c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notificacao",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("proposta_candidata", "atualizacao_api", "edicao_manual", name="notificacao_tipo"),
            nullable=False,
        ),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("corpo", sa.String(), nullable=True),
        sa.Column("entidade_id", sa.BigInteger(), nullable=False),
        sa.Column("nivel_minimo", sa.String(), nullable=True),
        sa.Column("lida", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_notificacao_lida_created", "notificacao", ["lida", "created_at"], unique=False)
    op.create_table(
        "proposta_candidata",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("id_proposta", sa.BigInteger(), nullable=False),
        sa.Column("cnpj_ente_recebedor", sa.String(), nullable=False),
        sa.Column("nm_proponente", sa.String(), nullable=False),
        sa.Column("municipio", sa.String(), nullable=True),
        sa.Column("uf", sa.String(length=2), nullable=True),
        sa.Column("ds_objeto", sa.String(), nullable=False),
        sa.Column("nm_programa", sa.String(), nullable=False),
        sa.Column("id_programa", sa.BigInteger(), nullable=False),
        sa.Column("componente_batido", sa.String(), nullable=False),
        sa.Column("equipamento_detectado", sa.String(), nullable=True),
        sa.Column("vl_global_proposta", sa.Numeric(), nullable=True),
        sa.Column("situacao_proposta", sa.String(), nullable=True),
        sa.Column("data_proposta", sa.Date(), nullable=True),
        sa.Column("metas_resumo", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tem_parceria", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pendente", "aceita", "rejeitada", name="proposta_candidata_status"),
            server_default="pendente",
            nullable=False,
        ),
        sa.Column("revisado_por", sa.BigInteger(), nullable=True),
        sa.Column("revisado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["revisado_por"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id_proposta"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("proposta_candidata")
    op.drop_index("ix_notificacao_lida_created", table_name="notificacao")
    op.drop_table("notificacao")
    # ### end Alembic commands ###
