"""adiciona tabela municipality_coverage

Revision ID: d5c54063c1fb
Revises: f0ab29cc43ec
Create Date: 2026-08-21 14:59:16.476130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd5c54063c1fb'
down_revision: Union[str, Sequence[str], None] = 'f0ab29cc43ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipality_coverage',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('execution_id', sa.BigInteger(), nullable=False),
    sa.Column('ibge_code', sa.String(), nullable=False),
    sa.Column('municipality_name', sa.String(), nullable=False),
    sa.Column('health_region_code', sa.String(), nullable=True),
    sa.Column('health_region_name', sa.String(), nullable=True),
    sa.Column('macro_code', sa.String(), nullable=True),
    sa.Column('macro_name', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('equipment_family', sa.String(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('population_residente', sa.Integer(), nullable=True),
    sa.Column('population_ans', sa.Integer(), nullable=True),
    sa.Column('estimated_need', sa.Numeric(), nullable=True),
    sa.Column('required_qty', sa.Integer(), nullable=True),
    sa.Column('available_qty', sa.Integer(), nullable=True),
    sa.Column('existing_qty', sa.Integer(), nullable=True),
    sa.Column('facility_count', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('deficit_status', postgresql.ENUM('deficient', 'not_deficient', 'not_available', name='deficit_status', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_municipality_coverage_execution_family', 'municipality_coverage', ['execution_id', 'equipment_family'], unique=False)
    op.create_index('ix_municipality_coverage_execution_health_region', 'municipality_coverage', ['execution_id', 'health_region_code'], unique=False)
    op.create_index('ix_municipality_coverage_execution_macro', 'municipality_coverage', ['execution_id', 'macro_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_municipality_coverage_execution_macro', table_name='municipality_coverage')
    op.drop_index('ix_municipality_coverage_execution_health_region', table_name='municipality_coverage')
    op.drop_index('ix_municipality_coverage_execution_family', table_name='municipality_coverage')
    op.drop_table('municipality_coverage')
    # ### end Alembic commands ###
