"""adiciona population_residente e population_ans em macro_coverage

Revision ID: f0ab29cc43ec
Revises: b3a934a59718
Create Date: 2026-08-21 14:41:08.303129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ab29cc43ec'
down_revision: Union[str, Sequence[str], None] = 'b3a934a59718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('macro_coverage', sa.Column('population_residente', sa.Integer(), nullable=True))
    op.add_column('macro_coverage', sa.Column('population_ans', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('macro_coverage', 'population_ans')
    op.drop_column('macro_coverage', 'population_residente')
    # ### end Alembic commands ###
