"""adiciona distancia ate equipamento mais proximo em municipality_coverage

Revision ID: f599d15640e4
Revises: 5066a7877a2c
Create Date: 2026-08-23 11:01:02.052653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f599d15640e4'
down_revision: Union[str, Sequence[str], None] = '5066a7877a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('municipality_coverage', sa.Column('distance_km_nearest_equipment', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('municipality_coverage', 'distance_km_nearest_equipment')
    # ### end Alembic commands ###
