"""remove_cpf_hash_contrato_morto

Revision ID: f8fe7ce9347c
Revises: efd3e49db7f8
Create Date: 2026-09-17 08:18:27.443204

Plan Mode seguranca 2026-09-16, Bloco 5: `cpf_hash` nunca teve fluxo real
de captura/hash de CPF (schema `UserCreate.cpf` nunca foi importado em
nenhum router; `scripts/criar_usuario.py` gravava o sentinela literal
"nao-informado"). Confirmado antes desta migration que nao ha valor real
alem de "nao-informado" em producao (`SELECT DISTINCT cpf_hash FROM
"user"` no Neon). Decisao do usuario: remover o contrato morto em vez de
implementar de verdade.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fe7ce9347c'
down_revision: Union[str, Sequence[str], None] = 'efd3e49db7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cpf_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cpf_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
